### ISSUE TITLE
TODO: ask read count and like count

### ISSUE THREAD

**Issue by kaizsv** [yiwei1116/AndroidITRI#1]
string name problem and multi select problem
mode --> read count & like count
zone --> like count
mode, zone, device --> read count & like count have to be uploaded to server.

**Comment by kaizsv** [comment]
TODO: survey upload
There are several survey upload problem need to be fix.

**Comment by kaizsv** [comment]
Sound player list

**Comment by kaizsv** [comment]
map fragment tour visibility

**Comment by kaizsv** [comment]
mode picture

**Comment by kaizsv** [comment]
button sound effect

**Comment by kaizsv** [comment]
page picture

**Comment by kaizsv** [comment]
duplicate sqlite row

download more pictrure @1x @2x @3x

**Comment by kaizsv** [comment]
beacon zone number

**Comment by Boopslo** [comment]
how frequent should the like_count & read_count be uploaded to server ?

**Comment by kaizsv** [comment]
youtube fragment

**Comment by kaizsv** [comment]
map fragment set toolbar title
